\c postgres;

DROP DATABASE IF EXISTS emp_db;

CREATE DATABASE emp_db;

\c emp_db;

CREATE TABLE dept (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE role (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) UNIQUE NOT NULL,
  salary DECIMAL NOT NULL,
  dept_id INTEGER NOT NULL,
  FOREIGN KEY (dept_id)
  REFERENCES dept(id)
  ON DELETE SET NULL
);

CREATE TABLE employees (
  id SERIAL PRIMARY KEY,
  first VARCHAR(100) NOT NULL,
  last VARCHAR(100) NOT NULL,
  role_id INTEGER NOT NULL,
  manager_id INTEGER,
  FOREIGN KEY (role_id)
  REFERENCES role(id)
  ON DELETE SET NULL
);
